server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # Nacos服务注册中心地址
        #server-addr: localhost:8848
        server-addr: 192.168.0.105:1111
    sentinel:
      transport:
        # sentinel dashboard 地址
        dashboard: localhost:8080
        # 默认为8719，如果被占用会自动+1，直到找到为止
        port: 8719
      # 流控规则持久化到nacos
      datasource:
        dsl:
          nacos:
#            server-addr: localhost:8848
            server-addr: 192.168.0.105:1111
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

  http:
    encoding:
      force-response: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

